global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "heartsight_metrics"
    static_configs:
      # For Docker on Windows: use host.docker.internal to reach host machine
      - targets: ["host.docker.internal:9000"]
